{% set name = "python-bidi" %}
{% set version = "0.5.1" %}
{% set sha256 = "3375bd95295d70738576e65bfb3c0ec3759343d0c01d9eb1ee28ac7d847773ea" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - pybidi = bidi:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six

test:
  imports:
    - bidi
  commands:
    - pybidi --help

about:
  home: https://github.com/MeirKriheli/python-bidi
  license: LGPLv3
  license_family: LGPL
  license_file: 'COPYING.LESSER'
  summary: Pure python implementation of the BiDi layout algorithm
  description: Bi-directional (BiDi) layout implementation in pure python
  doc_url: http://python-bidi.readthedocs.io/en/latest/
  dev_url: https://github.com/MeirKriheli/python-bidi

extra:
  recipe-maintainers:
    - kastman
