{% set name = "python-bidi" %}
{% set version = "0.6.3" %}
{% set sha256 = "e12114969001a328aea859f79efc30ab9c15241befb86e07029d8961d97fae36" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<39 or py>312]
  number: 0
  entry_points:
    - pybidi = bidi:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python

test:
  imports:
    - bidi
  commands:
    - pip check
    - pybidi --help
  requires:
    - pip

about:
  home: https://github.com/MeirKriheli/python-bidi
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: 'COPYING.LESSER'
  summary: Pure python implementation of the BiDi layout algorithm
  description: Bi-directional (BiDi) layout implementation in pure python
  doc_url: http://python-bidi.readthedocs.io/en/latest/
  dev_url: https://github.com/MeirKriheli/python-bidi

extra:
  recipe-maintainers:
    - thewchan
    - kastman
